### ISSUE TITLE
How to speedup in Linux system

### ISSUE THREAD

**Issue by jiawei151** [Xrvitd/NormalOrientation#10]
Thank you for your great work! You mentioned in README that enabling **AVX2** and **Floating Point Model** will speedup the GCNO. I am wondering how to achieve them in a Ubuntu system (without GUI). For instance, I added the following line to CMakeLists.txt to support OpenMP, `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp -pthread")`. 
Unfortunately I am not familiar with VS in Windows. Would you have some idea for that? Thanks a lot!

**Comment by jiawei151** [comment]
BTW, I installed the dependencies via VCPKG for Unix.

**Comment by Xrvitd** [comment]
Sorry, I'm not using Ubuntu to run this code. If openMP is successfully enabled, the speed should be sufficient. ACX2 will increase speed, but only a little.

**Comment by jiawei151** [comment]
> Sorry, I'm not using Ubuntu to run this code. If openMP is successfully enabled, the speed should be sufficient. ACX2 will increase speed, but only a little.

I got it. Actually, the situation I try to deal with is a point cloud with 10k points, which seems to be really time-consuming. Thanks anyway.
