### ISSUE TITLE
Open surface reconstruction

### ISSUE THREAD

**Issue by Enamel2** [Xrvitd/NormalOrientation#11]
Thank you for the amazing work! I'm impressed by the design of the algorithm and the accuracy your work achieved. Recently during my work, I'm trying to apply such algorithm to estimate normals from a point cloud sampled from an open surface. As far as I know the screened poisson reconstruction will create closed watertight surface. So may I ask what's the good way to reconstruct an open surface once the normal is estimated? Your answer will be deeply appreciated! Thanks!

**Comment by Xrvitd** [comment]
Try to use some Explicit Reconstruction methods? Or maybe u can just cut off your PSR result.
















At 2024-07-13 05:58:03, "Enamel2" ***@***.***> wrote:

Thank you for the amazing work! I'm impressed by the design of the algorithm and the accuracy your work achieved. Recently during my work, I'm trying to apply such algorithm to estimate normals from a point cloud sampled from an open surface. As far as I know the screened poisson reconstruction will create closed watertight surface. So may I ask what's the good way to reconstruct an open surface once the normal is estimated? Your answer will be deeply appreciated! Thanks!
