### ISSUE TITLE
关于C++版本的问题

### ISSUE THREAD

**Issue by yu-jiahe** [Xrvitd/NormalOrientation#12]
![image](https://github.com/user-attachments/assets/cbadd707-f472-49c4-af45-97603a8b4e90)
15>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\cstddef(28,12): message : 或    “std::byte”
15>C:\src\vcpkg\installed\x64-windows\include\CGAL/ImageIO/iris_impl.h(454,20): error C2872: “byte”: 不明确的符号
15>C:\src\vcpkg\installed\x64-windows\include\CGAL/ImageIO/gif_impl.h(51,23): message : 可能是“unsigned char byte”
在ALL BULID的时候产生这样的报错，查了一下，是因为C++17 内部定义了std:[byte类型]，Windows系统定义了byte类型，如果使用using namespace std; 两个类型使用时可能会出现冲突。但是降低C++版本的话，会提示CGAL需要C++17以上的版本

我看到推荐使用的Visual Studio版本是2022，请问您是如何解决这个问题的

**Comment by yu-jiahe** [comment]
抱歉我在readme找到了是C++17

**Comment by crazyMessi** [comment]
请问是怎么解决的？ 我也是用c++17 也遇到了这个问题
