### ISSUE TITLE
部分模型运行错误

### ISSUE THREAD

**Issue by crazyMessi** [Xrvitd/NormalOrientation#3]
学长您好，非常感谢您的代码
不过我在使用你们的代码运行自己的模型的时候，有的模型会在这一步卡住
![image](https://github.com/Xrvitd/GCNO/assets/56535498/04c07d12-6884-4302-bad0-55565de7d0da)
![image](https://github.com/Xrvitd/GCNO/assets/56535498/03a8ddaf-40a7-4c86-ae69-e7cb5c024d58)

**Comment by Xrvitd** [comment]
有可能是在计算空间voronoi图的时候出现了数值错误。可以试试把点云稍微抖动一下，或则重新采样一下试试
















在 2023-07-12 14:37:19，"zhuodong li" ***@***.***> 写道：

学长您好，非常感谢您的代码
不过我在使用你们的代码运行自己的模型的时候，有的模型会在这一步卡住

**Comment by crazyMessi** [comment]
> 有可能是在计算空间voronoi图的时候出现了数值错误。可以试试把点云稍微抖动一下，或则重新采样一下试试 在 2023-07-12 14:37:19，"zhuodong li" ***@***.***> 写道： 学长您好，非常感谢您的代码 不过我在使用你们的代码运行自己的模型的时候，有的模型会在这一步卡住 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

可以用 感谢
