### ISSUE TITLE
Visualisations in Paper

### ISSUE THREAD

**Issue by basit-7** [Xrvitd/NormalOrientation#4]
Hi, congratulations on the great work. The visualisations in the paper are really nice, what tool did you use for it?

**Comment by Xrvitd** [comment]
By 3ds max from autodesk.



| |
Rui Xu
Shandong University
***@***.***
Qingdao, China
|




---- Replied Message ----
| From | Abdul ***@***.***> |
| Date | 07/17/2023 18:27 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [Xrvitd/GCNO] Visualisations in Paper (Issue #4) |

Hi, congratulations on the great work. The visualisations in the paper are really nice, what tool did you use for it?

**Comment by basit-7** [comment]
Did you use Autodesk 3ds max for all of these?

<img width="1255" alt="image" src="https://github.com/Xrvitd/GCNO/assets/67473743/f50bc4fc-5e4a-4b6b-b0fd-fb6556a98a5e">

**Comment by Xrvitd** [comment]
Only about two or three figs was made by blender.



| |
Rui Xu
Shandong University
***@***.***
Qingdao, China
|




---- Replied Message ----
| From | Abdul ***@***.***> |
| Date | 07/17/2023 20:13 |
| To | ***@***.***> |
| Cc | Rui ***@***.***>***@***.***> |
| Subject | Re: [Xrvitd/GCNO] Visualisations in Paper (Issue #4) |

Did you use Autodesk 3ds max for all of these?

**Comment by Xrvitd** [comment]
This fig is 3ds max and matlab for the 2d fields.



| |
Rui Xu
Shandong University
***@***.***
Qingdao, China
|




---- Replied Message ----
| From | Abdul ***@***.***> |
| Date | 07/17/2023 20:13 |
| To | ***@***.***> |
| Cc | Rui ***@***.***>***@***.***> |
| Subject | Re: [Xrvitd/GCNO] Visualisations in Paper (Issue #4) |

Did you use Autodesk 3ds max for all of these?

**Comment by basit-7** [comment]
Great, thanks!
