### ISSUE TITLE
License of the source code

### ISSUE THREAD

**Issue by yxlao** [Xrvitd/NormalOrientation#5]
Thank you for the excellent work. It would be very helpful if you could specify the license type (e.g., MIT, Apache, etc.). Thank you!

**Comment by MorganeExtrality** [comment]
The code is under BDS License. You can find the info here: https://github.com/Xrvitd/GCNO/blob/master/MAIN/nanoflann.hpp

**Comment by Xrvitd** [comment]
Sorry for the late update, we have added the license of our code  GPL-3.0 license).
