### ISSUE TITLE
点云数量较多可以吗？

### ISSUE THREAD

**Issue by wjiangsheng** [Xrvitd/NormalOrientation#7]
我试了4000个点运行非常快，但是我有个大模型点云，大概200w个点，一晚上也没运行出来结果，我试着精简到20w点，依旧没运行踹结果。

**Comment by wjiangsheng** [comment]
> 

如果继续精简的话，丢失特征太多了

**Comment by Frank-ZY-Dou** [comment]
> 我试了4000个点运行非常快，但是我有个大模型点云，大概200w个点，一晚上也没运行出来结果，我试着精简到20w点，依旧没运行踹结果。

Hi @wjiangsheng, thanks for your interest in this work. 
As we discussed in Sec. 6 of the main paper, processing super large-scale point clouds typically requires a long optimization time that can take longer than a night. Therefore, achieving a balance between geometric accuracy after downsampling and runtime performance becomes crucial, which may need more finetuning to achieve such a balance.

**Comment by wjiangsheng** [comment]
> > 我试了4000个点运行非常快，但是我有个大模型点云，大概200w个点，一晚上也没运行出来结果，我试着精简到20w点，依旧没运行踹结果。
> 
> 嗨，感谢您对这项工作的关注。正如我们在主要论文的第6节中所讨论的，处理超大规模点云通常需要很长的优化时间，可能需要超过一个晚上的时间。因此，在缩减采样后的几何精度和运行时性能之间实现平衡变得至关重要，这可能需要更多微调才能实现这种平衡。

Thank you!I'll wait and see the results after the execution.

**Comment by Xrvitd** [comment]
@wjiangsheng  According to our experiments, the running time will increase several times after exceeding 10w points. In our test on the Intel i9 13900k CPU, it takes more than 24 hours for 8w points. If you use 20w points, the time may reach several days or even weeks...

**Comment by wjiangsheng** [comment]
> 

ok，thank you！
