### ISSUE TITLE
带颜色的点可以计算吗？

### ISSUE THREAD

**Issue by moyu026** [Xrvitd/NormalOrientation#8]
我的xyz文件里是带rgb的，下面的这样，然后运行的时候就会卡住，需要把rgb值去掉吗?
633.47131348 318.81649780 27.76199913 120 119 125 -0.887054 0.459197 0.047691
633.44989014 318.81320190 26.36639977 138 136 139 -0.865518 -0.413678 -0.282400
633.51312256 318.63931274 26.98979950 80 75 81 -0.546041 -0.223031 -0.807525
633.50170898 318.67001343 27.90789986 51 46 52 -0.416320 -0.892115 0.175522

**Comment by Xrvitd** [comment]
Hi, you need to change your input file to:
[x,y,z,nx,ny,nz]
or
[x,y,z,0,0,0]
pls make sure you have 6 number for each line.
















在 2023-08-10 11:07:24，"moyu026" ***@***.***> 写道：

我的xyz文件里是带rgb的，下面的这样，然后运行的时候就会卡住，需要把rgb值去掉吗?
633.47131348 318.81649780 27.76199913 120 119 125 -0.887054 0.459197 0.047691
633.44989014 318.81320190 26.36639977 138 136 139 -0.865518 -0.413678 -0.282400
633.51312256 318.63931274 26.98979950 80 75 81 -0.546041 -0.223031 -0.807525
633.50170898 318.67001343 27.90789986 51 46 52 -0.416320 -0.892115 0.175522
