### ISSUE TITLE
How to get the reconstruct surface?

### ISSUE THREAD

**Issue by Connaught0** [Xrvitd/NormalOrientation#9]
Hi! thanks for your excellent work! I try your released code and run well on demo data. But how could I generate the mesh in the paper?
ex.
![image](https://github.com/Xrvitd/GCNO/assets/37895469/706c9d39-d81c-4799-87cf-9cac534265af)

**Comment by Xrvitd** [comment]
Hi！ We all use screened Poisson reconstruction to get the mesh.

| |
Rui Xu
Shandong University
***@***.***
Qingdao, China
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/07/2023 10:59 |
| To | Xrvitd/GCNO ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [Xrvitd/GCNO] How to get the reconstruct surface? (Issue #9) |

Hi! thanks for your excellent work! I try your released code and run well on demo data. But how could I generate the mesh in the paper?
ex.

**Comment by Connaught0** [comment]
> Hi！ We all use screened Poisson reconstruction to get the mesh. | | Rui Xu Shandong University ***@***.*** Qingdao, China | ---- Replied Message ---- | From | ***@***.***> | | Date | 11/07/2023 10:59 | | To | Xrvitd/GCNO ***@***.***> | | Cc | Subscribed ***@***.***> | | Subject | [Xrvitd/GCNO] How to get the reconstruct surface? (Issue #9) | Hi! thanks for your excellent work! I try your released code and run well on demo data. But how could I generate the mesh in the paper? ex. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

thanks！ I have tried in meshlab, it's work : )
